[package]
name = "snapcast-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
snapcast-proto = { workspace = true }
snapcast-client = { workspace = true }
snapcast-server = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
