[package]
name = "snapserver-rs"
description = "Snapcast server — synchronized multiroom audio server"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "snapserver-rs"
path = "src/main.rs"

[dependencies]
snapcast-server = { workspace = true }
snapcast-proto = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust-ini = "0.21"
jsonwebtoken = { version = "11.1", features = ["rust_crypto"] }
base64 = { workspace = true }
subtle = { workspace = true }
tempfile = "3"
libc = { workspace = true }
axum = { version = "0.8.8", features = ["ws"] }
tower-http = { version = "0.7.1", features = ["fs"] }
futures-util = { workspace = true }

[dev-dependencies]
snapcast-client = { workspace = true, features = ["websocket"] }
tokio-tungstenite = { workspace = true }

[features]
default = ["snapcast-server/default"]
flac = ["snapcast-server/flac"]
opus = ["snapcast-server/opus"]
